select insertkayttooikeus('KOSKI', 'KAIKKI_OPISKELUOIKEUS_TYYPIT', 'Saa nähdä kaiken tyyppiset opiskeluoikeudet');
select insertkayttooikeus('KOSKI', 'AIKUISTENPERUSOPETUS', 'Saa nähdä aikuisten perusopetuksen opiskeluoikeuksia');
select insertkayttooikeus('KOSKI', 'AMMATILLINENKOULUTUS', 'Saa nähdä ammatillisia opiskeluoikeuksia');
select insertkayttooikeus('KOSKI', 'DIATUTKINTO', 'Saa nähdä DIA-tutkinnon opiskeluoikeuksia');
select insertkayttooikeus('KOSKI', 'ESIOPETUS', 'Saa nähdä esiopetuksen opiskeluoikeuksia');
select insertkayttooikeus('KOSKI', 'IBTUTKINTO', 'Saa nähdä IB-tutkinnon opiskeluoikeuksia');
select insertkayttooikeus('KOSKI', 'INTERNATIONALSCHOOL', 'Saa nähdä International school opiskeluoikeuksia');
select insertkayttooikeus('KOSKI', 'KORKEAKOULUTUS', 'Saa nähdä korkeakoulujen opiskeluoikeuksia');
select insertkayttooikeus('KOSKI', 'LUKIOKOULUTUS', 'Saa nähdä lukiokoulutuksen opiskeluoikeuksia');
select insertkayttooikeus('KOSKI', 'LUVA', 'Saa nähdä lukioon valmistavan koulutuksen opiskeluoikeuksia');
select insertkayttooikeus('KOSKI', 'PERUSOPETUKSEENVALMISTAVAOPETUS', 'Saa nähdä perusopetukseen valmistavan opetuksen opiskeluoikeuksia');
select insertkayttooikeus('KOSKI', 'PERUSOPETUKSENLISAOPETUS', 'Saa nähdä perusopetuksen lisäopetuksen opiskeluoikeuksia');
select insertkayttooikeus('KOSKI', 'PERUSOPETUS', 'Saa nähdä nuorten perusopetuksen opiskeluoikeuksia');
select insertkayttooikeus('KOSKI', 'YLIOPPILASTUTKINTO', 'Saa nähdä ylioppilastutkinnon opiskeluoikeuksia');
